#:kivy 2.1.0
<FileChoosePopUpWidget>
    orientation: 'vertical'
    FileChooser:
        id: fc
        size_hint_y: 0.9
        dirselect: True
        filters: [root.isDir]
        FileChooserListLayout
    BoxLayout:
        size_hint_y: 0.1
        Button:
            id: chooseBottun
            text: '選択'
            on_release: root.bottunChoose()
        Button:
            text: 'キャンセル'
            on_release: root.dismiss()
